# Generated by Django 4.0.2 on 2022-11-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dldevice',
            name='is_closed',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='dldevice',
            name='is_locked',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='dldevice',
            name='type',
            field=models.CharField(default='Door', max_length=30),
        ),
    ]
