# Generated by Django 4.0.2 on 2022-11-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dldevice_is_closed_dldevice_is_locked_dldevice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dldevice',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
