# Generated by Django 4.0.2 on 2023-02-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dldevice',
            old_name='namekey',
            new_name='device_access_key',
        ),
        migrations.RenameField(
            model_name='dldevice',
            old_name='passkey',
            new_name='hw_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='trigger',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_token',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
