# Generated by Django 4.0.2 on 2023-02-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_namekey_dldevice_device_access_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dldevice',
            name='HW_updates',
            field=models.JSONField(default=False),
        ),
        migrations.AddField(
            model_name='dldevice',
            name='UI_updates',
            field=models.JSONField(default=False),
        ),
    ]
