# Generated by Django 4.0.2 on 2023-02-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_dldevice_hw_updates_alter_dldevice_ui_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='dldevice',
            name='last_update',
            field=models.CharField(default='', max_length=30),
        ),
    ]
