# Generated by Django 4.0.2 on 2023-02-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dldevice_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dldevice',
            name='last_update',
            field=models.DateTimeField(),
        ),
    ]
