# Generated by Django 4.0.2 on 2023-02-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_dldevice_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dldevice',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
