'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import Button from './components/Button/Button'
import { useRouter } from 'next/navigation'
const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const router = useRouter()

  return (
    <html lang="en">
      <body className={inter.className}>
        
        <nav className="flex justify-evenly py-4 border-b mb-4">
          <Button lable="Home" onClick={()=>router.push('/')}/>
          <Button lable="Login" onClick={()=>router.push('/login')}/>
        </nav>
        {children}
      </body>
    </html>
  )
}
