version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  nextjs:
    image: iotstation-nextjs
    network_mode: "bridge"
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    cap_add:
      - NET_ADMIN
    privileged: true

